@baseUrl=http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJuaWNvbGFzLmp1bmNvc0BnbWFpbC5jb20iLCJpYXQiOjE3NTI3MjgwMDMsImV4cCI6MTc1MjczMTYwM30.BPoWeX1sFhtMlJ8bufX8BR5N4tjiAq7885YcXYl3prQ

### Register a new user
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Nicolas Juncos",
  "email": "nicolas.juncos@gmail.com",
  "password": "password123"
}

### Login user
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "nicolas.juncos@gmail.com",
  "password": "password123"
}

### Create a new post
POST {{baseUrl}}/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "New Post 4",
  "content": "This is the content of the new post."
}